### ISSUE TITLE
请问是否有ppt格式的文件分享？

### ISSUE THREAD

**Issue by kingxiaofire** [secdr/research-method#2]
如题，我非常需要how to write / 撰写基金申请书的一点肤浅体会（PPT版）—李红谊教授.pdf 的ppt文件，如果有可以分享给我吗？
我的邮箱：kingxiaofire@outlook.com，感激不尽。

**Comment by xizero00** [comment]
https://www.sohu.com/a/522821461_121123740

> 如题，我非常需要how to write / 撰写基金申请书的一点肤浅体会（PPT版）—李红谊教授.pdf 的ppt文件，如果有可以分享给我吗？ 我的邮箱：[kingxiaofire@outlook.com](mailto:kingxiaofire@outlook.com)，感激不尽。
